version: "3.8"

# This configuration is for running headscale
# on a server with a public IP address (e.g. a VPS)
#
# For connecting your home server to the Headscale network,
# please checkout the headscale-client/ directory.

  headscale:
    image: "headscale/headscale:latest"
    container_name: "headscale"
    command: serve
    restart: unless-stopped
    ports:
      - "9500:9500" # Port untuk Headscale
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    environment:
      - HEADSCALE_LOG_LEVEL=info
      - HEADSCALE_SERVER_URL=http://localhost:9500
